# Generated by Django 4.2 on 2023-08-08 17:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("musicians", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("birthdate", models.DateField()),
                ("gender", models.CharField(max_length=20)),
                ("email", models.CharField(max_length=60)),
            ],
        ),
    ]
